version: '3'

services:
  discordbot:
    container_name: slackbot
    image: ekolp/slackbot:dev
    platform: linux/amd64
    environment:
      SLACK_BOT_TOKEN: ''
      SLACK_SIGNING_SECRET: ''
      SLACK_APP_TOKEN: ''
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: slack_notes
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    container_name: db
    image: percona/percona-server:8.0.39
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
      # This auto-loads our base db and schema without 3rd party tools or scripts.
      - ./slackbotdb.sql:/docker-entrypoint-initdb.d/1.sql
    healthcheck:
      # Truth be told, I don't really care what this returns as long as it exits zero.
      test: bash -c "/usr/bin/netstat -ltn | grep -c 3306"
      interval: 15s
      retries: 5
      start_period: 20s # This controls the startup delay of the Liquibase container.
      timeout: 5s

volumes:
  my-db: