FROM liquibase/liquibase:4.29

# Install the MySQL JDBC driver into the Liquibase lib directory
USER root
RUN curl -L -o /liquibase/lib/mysql-connector-j.jar \
    https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.4.0/mysql-connector-j-8.4.0.jar
USER liquibase
